name: Jobs

on: [push]

env:
  CARGO_TERM_COLOR: always
<<<<<<< HEAD
<<<<<<< HEAD
  rust_toolchain: nightly

jobs:
  build-doc:
    if: github.repository == 'LearningOS/rCore-Camp-Code-2025S'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build doc
        run: |
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2025S.git user
=======
  rust_toolchain: nightly-2022-08-05
=======
  rust_toolchain: nightly
>>>>>>> 2023A

jobs:
  build-doc:
    if: github.repository == 'LearningOS/rCore-Tutorial-Code-2023A'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build doc
        run: |
<<<<<<< HEAD
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2023S.git user
>>>>>>> Chapter 2
=======
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2023A.git user
>>>>>>> 2023A
          cd os
          make
          cargo doc --no-deps --verbose
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./os/target/riscv64gc-unknown-none-elf/doc
          destination_dir: ${{ github.ref_name }}
  basic-test:
    runs-on: ubuntu-latest
<<<<<<< HEAD
<<<<<<< HEAD
    outputs:
      points: ${{ steps.end.outputs.points}}
    container:
      image: duskmoon/dev-env:rcore-ci
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
=======
=======
    outputs:
      points: ${{ steps.end.outputs.points}}
>>>>>>> Chapter 3
    container:
      image: duskmoon/dev-env:rcore-ci
    steps:
      - uses: actions/checkout@v3
>>>>>>> Chapter 2
=======
>>>>>>> 2023A
      - name: Run tests
        run: |
          qemu-system-riscv64 --version
          rustup target add riscv64gc-unknown-none-elf
<<<<<<< HEAD
<<<<<<< HEAD
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          git clone https://github.com/LearningOS/rCore-Tutorial-Checker-2025S.git ci-user
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2025S.git ci-user/user
          ID=`git rev-parse --abbrev-ref HEAD | grep -oP 'ch\K[0-9]'`
          # cd ci-user && make test CHAPTER=$ID passwd=${{ secrets.BASE_TEST_TOKEN }}
          cd ci-user && make test CHAPTER=$ID passwd=${{ secrets.BASE_TEST_TOKEN }} > ../output.txt
          cat ../output.txt
      - name: end
        id: end
        run: |
          cat output.txt | grep -a "Test passed" | grep -oP "\d{1,}/\d{1,}" | xargs -i echo "points={}"
          cat output.txt | grep -a "Test passed" | grep -oP "\d{1,}/\d{1,}" | xargs -i echo "points={}" >> $GITHUB_OUTPUT
  deploy:
    if: github.repository != 'LearningOS/rCore-Camp-Code-2025S'
    name: Deploy to pages
    needs: basic-test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: 'gh-pages'
      - name: Save Log File
        uses: yfblock/multi-rank-log@main
        with:
          public-dir: classroom
          points: ${{ needs.basic-test.outputs.points }}
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./classroom
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check score
        env:
          course_id: ${{ secrets.RCORE_2025_SPRING_COURSE_ID }}
          post_api: ${{ secrets.RCORE_2025_SPRING_POST_API }}
          token: ${{ secrets.RCORE_2025_SPRING_TOKEN }}
        run: |
          score=$(( $(grep -o 'ch' classroom/latest.json | wc -l) * 100))
          cat classroom/latest.json
          echo $score

          github_user="${{ github.actor }}"

          # 生成 JSON 结果
          score_json=$(jq -n \
            --arg channel "github" \
            --argjson courseId "$course_id" \
            --arg name "$github_user" \
            --argjson score "$score" \
            --argjson totalScore 500 \
            '{channel: $channel, courseId: $courseId, name: $name, score: $score, totalScore: $totalScore}')

            response=$(curl -X POST $post_api \
            -H "accept: application/json;charset=utf-8" \
            -H "Content-Type: application/json" \
            -H "token: $token" \
            -d "$score_json" \
            -v)

            echo "Response: $response"

            if echo "$response" | grep -q '"result":1'; then
            echo "Success: The result field contains 1."
            else
            echo "Error: The result field does not contain 1."
            exit 1
            fi
=======
          git config --global --add safe.directory /__w/rCore-Tutorial-Code-2023S/rCore-Tutorial-Code-2023S
=======
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
<<<<<<< HEAD
>>>>>>> update safe.directory
          git clone https://github.com/LearningOS/rCore-Tutorial-Checker-2023S.git ci-user
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2023S.git ci-user/user
=======
          git clone https://github.com/LearningOS/rCore-Tutorial-Checker-2023A.git ci-user
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2023A.git ci-user/user
>>>>>>> 2023A
          ID=`git rev-parse --abbrev-ref HEAD | grep -oP 'ch\K[0-9]'`
          cd ci-user && make test CHAPTER=$ID passwd=${{ secrets.BASE_TEST_TOKEN }} > ../output.txt
          # cd ci-user && make test CHAPTER=$ID passwd=${{ secrets.BASE_TEST_TOKEN }}
          cat ../output.txt
      - name: end
        id: end
        run: |
          cat output.txt | grep -a "Test passed" | grep -oP "\d{1,}/\d{1,}" | xargs -i echo "points={}"
          cat output.txt | grep -a "Test passed" | grep -oP "\d{1,}/\d{1,}" | xargs -i echo "points={}" >> $GITHUB_OUTPUT
  gitlab-mirror:
    if: github.repository == 'LearningOS/rCore-Tutorial-Code-2023A'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Mirror + trigger CI
      uses: tkf2019/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.tsinghua.edu.cn/os-lab/2023a/public/rcore-tutorial-code-2023a"
      env:
        GITLAB_HOSTNAME: "git.tsinghua.edu.cn"
<<<<<<< HEAD
        GITLAB_PROJECT_ID: "20881"
        GITLAB_PROJECT_NAME: "rcore-tutorial-code-2023s"
<<<<<<< HEAD
        GITLAB_PROJECT_TOKEN: ${{secrets.GITLAB_PROJECT_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
>>>>>>> Chapter 2
=======
        GITLAB_PROJECT_TOKEN: ${{ secrets.GITLAB_PROJECT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    if: github.repository != 'LearningOS/rCore-Tutorial-Code-2023S'
    name: Deploy to pages
    needs: basic-test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: 'gh-pages'
      - name: Save Log File
        uses: yfblock/multi-rank-log@main
        with:
          public-dir: classroom
          points: ${{ needs.basic-test.outputs.points }}
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./classroom
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
>>>>>>> Chapter 3
=======
>>>>>>> update safe.directory
=======
        GITLAB_PROJECT_ID: "26334"
        GITLAB_PROJECT_NAME: "rcore-tutorial-code-2023a"
        GITLAB_PROJECT_TOKEN: ${{ secrets.GITLAB_PROJECT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    if: github.repository != 'LearningOS/rCore-Tutorial-Code-2023A'
    name: Deploy to pages
    needs: basic-test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: 'gh-pages'
      - name: Save Log File
        uses: yfblock/multi-rank-log@main
        with:
          public-dir: classroom
          points: ${{ needs.basic-test.outputs.points }}
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./classroom
  #         keep_history: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 2023A
